[project]
name = "omm_hremd_Dan-Burns"
version = "0.0.1"
authors = [
  { name="Dan Burns", email="author@example.com" },
]
description = "Tools to script HREMD simulations "
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/"
"Bug Tracker" = "https://github.com/"

